In [1]:
import pandas as pd
import numpy as np

In [2]:
loans = pd.read_csv('lending-club-data.csv')

C:\Users\Dhaval-PC\Anaconda2\envs\gl-env\lib\site-packages\IPython\core\interactiveshell.py:2723: DtypeWarning: Columns (19,47) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
loans.head()

id  member_id  loan_amnt  funded_amnt  funded_amnt_inv        term  \
0  1077501    1296599       5000         5000             4975   36 months   
1  1077430    1314167       2500         2500             2500   60 months   
2  1077175    1313524       2400         2400             2400   36 months   
3  1076863    1277178      10000        10000            10000   36 months   
4  1075269    1311441       5000         5000             5000   36 months   

   int_rate  installment grade sub_grade          ...          sub_grade_num  \
0     10.65       162.87     B        B2          ...                    0.4   
1     15.27        59.83     C        C4          ...                    0.8   
2     15.96        84.33     C        C5          ...                    1.0   
3     13.49       339.31     C        C1          ...                    0.2   
4      7.90       156.46     A        A4          ...                    0.8   

  delinq_2yrs_zero pub_rec_zero  collections_12_mths_zero short_emp  \
0              1.0          1.0                       1.0         0   
1              1.0          1.0                       1.0         1   
2              1.0          1.0                       1.0         0   
3              1.0          1.0                       1.0         0   
4              1.0          1.0                       1.0         0   

  payment_inc_ratio          final_d last_delinq_none last_record_none  \
0           8.14350  20141201T000000                1                1   
1           2.39320  20161201T000000                1                1   
2           8.25955  20141201T000000                1                1   
3           8.27585  20141201T000000                0                1   
4           5.21533  20141201T000000                1                1   

  last_major_derog_none  
0                     1  
1                     1  
2                     1  
3                     1  
4                     1  

[5 rows x 68 columns]

In [4]:
loans.columns

Index([u'id', u'member_id', u'loan_amnt', u'funded_amnt', u'funded_amnt_inv',
       u'term', u'int_rate', u'installment', u'grade', u'sub_grade',
       u'emp_title', u'emp_length', u'home_ownership', u'annual_inc',
       u'is_inc_v', u'issue_d', u'loan_status', u'pymnt_plan', u'url', u'desc',
       u'purpose', u'title', u'zip_code', u'addr_state', u'dti',
       u'delinq_2yrs', u'earliest_cr_line', u'inq_last_6mths',
       u'mths_since_last_delinq', u'mths_since_last_record', u'open_acc',
       u'pub_rec', u'revol_bal', u'revol_util', u'total_acc',
       u'initial_list_status', u'out_prncp', u'out_prncp_inv', u'total_pymnt',
       u'total_pymnt_inv', u'total_rec_prncp', u'total_rec_int',
       u'total_rec_late_fee', u'recoveries', u'collection_recovery_fee',
       u'last_pymnt_d', u'last_pymnt_amnt', u'next_pymnt_d',
       u'last_credit_pull_d', u'collections_12_mths_ex_med',
       u'mths_since_last_major_derog', u'policy_code', u'not_compliant',
       u'status', u'inactiv

In [5]:
loans['safe_loans']=loans['bad_loans'].apply(lambda x: +1 if (x==0) else -1)

In [6]:
del loans['bad_loans']

In [7]:
loans.columns

Index([u'id', u'member_id', u'loan_amnt', u'funded_amnt', u'funded_amnt_inv',
       u'term', u'int_rate', u'installment', u'grade', u'sub_grade',
       u'emp_title', u'emp_length', u'home_ownership', u'annual_inc',
       u'is_inc_v', u'issue_d', u'loan_status', u'pymnt_plan', u'url', u'desc',
       u'purpose', u'title', u'zip_code', u'addr_state', u'dti',
       u'delinq_2yrs', u'earliest_cr_line', u'inq_last_6mths',
       u'mths_since_last_delinq', u'mths_since_last_record', u'open_acc',
       u'pub_rec', u'revol_bal', u'revol_util', u'total_acc',
       u'initial_list_status', u'out_prncp', u'out_prncp_inv', u'total_pymnt',
       u'total_pymnt_inv', u'total_rec_prncp', u'total_rec_int',
       u'total_rec_late_fee', u'recoveries', u'collection_recovery_fee',
       u'last_pymnt_d', u'last_pymnt_amnt', u'next_pymnt_d',
       u'last_credit_pull_d', u'collections_12_mths_ex_med',
       u'mths_since_last_major_derog', u'policy_code', u'not_compliant',
       u'status', u'inactiv

In [8]:
safe_loans = (loans[loans['safe_loans']==+1]['safe_loans'].count() / float(loans['safe_loans'].count()))*100
risky_loan = 100 - safe_loans

In [9]:
print("safe loan percentage: %s" % safe_loans)
print("risky loan percentage: %s" % risky_loan)

safe loan percentage: 81.1185331996
risky loan percentage: 18.8814668004


In [10]:
features = ['grade',                     # grade of the loan
            'sub_grade',                 # sub-grade of the loan
            'short_emp',                 # one year or less of employment
            'emp_length_num',            # number of years of employment
            'home_ownership',            # home_ownership status: own, mortgage or rent
            'dti',                       # debt to income ratio
            'purpose',                   # the purpose of the loan
            'term',                      # the term of the loan
            'last_delinq_none',          # has borrower had a delinquincy
            'last_major_derog_none',     # has borrower had 90 day or worse rating
            'revol_util',                # percent of available credit being used
            'total_rec_late_fee',        # total late fees received to day
           ]

target = 'safe_loans'                    # prediction target (y) (+1 means safe, -1 is risky)

# Extract the feature columns and target column
loans = loans[features + [target]]

In [11]:
loans.head()

grade sub_grade  short_emp  emp_length_num home_ownership    dti  \
0     B        B2          0              11           RENT  27.65   
1     C        C4          1               1           RENT   1.00   
2     C        C5          0              11           RENT   8.72   
3     C        C1          0              11           RENT  20.00   
4     A        A4          0               4           RENT  11.20   

          purpose        term  last_delinq_none  last_major_derog_none  \
0     credit_card   36 months                 1                      1   
1             car   60 months                 1                      1   
2  small_business   36 months                 1                      1   
3           other   36 months                 0                      1   
4         wedding   36 months                 1                      1   

   revol_util  total_rec_late_fee  safe_loans  
0        83.7                0.00           1  
1         9.4                0.00          -1  
2        98.5                0.00           1  
3        21.0               16.97           1  
4        28.3                0.00           1

In [12]:
categorical_variables = []
for feat_name, feat_type in zip(loans.columns, loans.dtypes):
    if feat_type == 'object':
        categorical_variables.append(feat_name)

loans_with_dummies = pd.get_dummies(loans[categorical_variables])
loans = loans.drop(categorical_variables, axis=1)
loans = loans.join(loans_with_dummies)

In [13]:
import json

with open('module-5-assignment-1-train-idx.json') as json_data:
    train_idx = json.load(json_data)
with open('module-5-assignment-1-validation-idx.json') as json_data:
    validation_idx = json.load(json_data)

In [14]:
train_data = loans.iloc[train_idx]
validation_data = loans.iloc[validation_idx]

In [15]:
loan_status_train_1 = train_data['safe_loans']
loan_status_valid_1 = validation_data['safe_loans']
train_data_1 = train_data.drop(['safe_loans'], axis=1)
validation_data_1 = validation_data.drop(['safe_loans'], axis=1)

In [16]:
from sklearn import tree
clf = tree.DecisionTreeClassifier(max_depth=6)

In [17]:
decision_tree_model = clf.fit(train_data_1.as_matrix(), loan_status_train_1.as_matrix())

In [27]:
clf_simple = tree.DecisionTreeClassifier(max_depth=2)
small_model = clf_simple.fit(train_data_1.as_matrix(), loan_status_train_1.as_matrix())

In [28]:
validation_safe_loans = validation_data[validation_data['safe_loans'] == 1]
validation_risky_loans = validation_data[validation_data['safe_loans'] == -1]

sample_validation_data_risky = validation_risky_loans[0:2]
sample_validation_data_safe = validation_safe_loans[0:2]

sample_validation_data = sample_validation_data_safe.append(sample_validation_data_risky)
sample_validation_data

short_emp  emp_length_num    dti  last_delinq_none  last_major_derog_none  \
19          0              11  11.18                 1                      1   
79          0              10  16.85                 1                      1   
24          0               3  13.97                 0                      1   
41          0              11  16.33                 1                      1   

    revol_util  total_rec_late_fee  safe_loans  grade_A  grade_B  \
19        82.4                 0.0           1      0.0      1.0   
79        96.4                 0.0           1      0.0      0.0   
24        59.5                 0.0          -1      0.0      0.0   
41        62.1                 0.0          -1      1.0      0.0   

         ...         purpose_house  purpose_major_purchase  purpose_medical  \
19       ...                   0.0                     0.0              0.0   
79       ...                   0.0                     0.0              0.0   
24       ...                   0.0                     0.0              0.0   
41       ...                   0.0                     0.0              0.0   

    purpose_moving  purpose_other  purpose_small_business  purpose_vacation  \
19             0.0            0.0                     0.0               0.0   
79             0.0            0.0                     0.0               0.0   
24             0.0            1.0                     0.0               0.0   
41             0.0            0.0                     0.0               0.0   

    purpose_wedding  term_ 36 months  term_ 60 months  
19              0.0              1.0              0.0  
79              0.0              1.0              0.0  
24              0.0              0.0              1.0  
41              0.0              1.0              0.0  

[4 rows x 68 columns]

In [29]:
decision_tree_model.predict(sample_validation_data.drop(['safe_loans'], axis=1))

array([ 1, -1, -1,  1], dtype=int64)

In [30]:
decision_tree_model.predict_proba(sample_validation_data.drop(['safe_loans'], axis=1))[:,1]

array([ 0.65843457,  0.46369354,  0.35249042,  0.79210526])

In [31]:
small_model.predict_proba(sample_validation_data.drop(['safe_loans'], axis=1))[:,1]

array([ 0.58103415,  0.40744661,  0.40744661,  0.76879888])

In [32]:
train_accuracy = decision_tree_model.score(train_data_1, loan_status_train_1)

In [33]:
print train_accuracy

0.640527616591


In [34]:
train_accuracy_small = small_model.score(train_data_1, loan_status_train_1)

In [35]:
print train_accuracy_small

0.613502041694


In [36]:
validation_accuracy = decision_tree_model.score(validation_data_1, loan_status_valid_1)
validation_accuracy_small = small_model.score(validation_data_1, loan_status_valid_1)

In [37]:
print validation_accuracy
print validation_accuracy_small

0.636148211978
0.619345109866


In [38]:
clf_big = tree.DecisionTreeClassifier(max_depth=10)
big_model = clf_big.fit(train_data_1, loan_status_train_1)

In [40]:
big_model_accuracy = big_model.score(train_data_1, loan_status_train_1)

In [41]:
print big_model_accuracy

0.663845905867


In [42]:
big_model_accuracy_valid = big_model.score(validation_data_1, loan_status_valid_1)

In [43]:
print big_model_accuracy_valid

0.626561826799


In [88]:
def cost(model, data, actual_value):
    prediction = model.predict(data)
    no_false_positive=0
    no_false_negative=0
    for predict, actual in zip(prediction, actual_value):
        if (predict == 1 and actual == -1):
            no_false_positive+=1
        elif (predict == -1 and actual == 1):
            no_false_negative+=1
    return ((no_false_positive * 20000) + (no_false_negative*10000))

In [89]:
cost = cost(decision_tree_model, validation_data_1, loan_status_valid_1)

In [90]:
print("Total Cost; %f" % cost)

Total Cost; 50390000.000000
