In [1]:
import graphlab

In [2]:
products = graphlab.SFrame('amazon_baby.gl/')

This non-commercial license of GraphLab Create for academic use is assigned to dhavalp576@gmail.com and will expire on May 27, 2018.


[INFO] graphlab.cython.cy_server: GraphLab Create v2.1 started. Logging: C:\Users\DHAVAL~1\AppData\Local\Temp\graphlab_server_1497158565.log.0


In [3]:
products.head()

Columns:
	name	str
	review	str
	rating	float

Rows: 10

Data:
+-------------------------------+-------------------------------+--------+
|              name             |             review            | rating |
+-------------------------------+-------------------------------+--------+
|    Planetwise Flannel Wipes   | These flannel wipes are OK... |  3.0   |
|     Planetwise Wipe Pouch     | it came early and was not ... |  5.0   |
| Annas Dream Full Quilt wit... | Very soft and comfortable ... |  5.0   |
| Stop Pacifier Sucking with... | This is a product well wor... |  5.0   |
| Stop Pacifier Sucking with... | All of my kids have cried ... |  5.0   |
| Stop Pacifier Sucking with... | When the Binky Fairy came ... |  5.0   |
| A Tale of Baby's Days with... | Lovely book, it's bound ti... |  4.0   |
| Baby Tracker&reg; - Daily ... | Perfect for new parents. W... |  5.0   |
| Baby Tracker&reg; - Daily ... | A friend of mine pinned th... |  5.0   |
| Baby Tracker&reg; - Daily ... | This has been an easy way ... |  4.0   |
+-------------------------------+-------------------------------+--------+
[10 rows x 3 columns]

In [4]:
products[269]

{'name': 'The First Years Massaging Action Teether',
 'rating': 5.0,
 'review': 'A favorite in our house!'}

In [5]:
def remove_punctuation(text):
    import string
    return text.translate(None, string.punctuation) 

products['review_clean'] = products['review'].apply(remove_punctuation)

In [7]:
products[269]

{'name': 'The First Years Massaging Action Teether',
 'rating': 5.0,
 'review': 'A favorite in our house!',
 'review_clean': 'A favorite in our house'}

In [19]:
products[products['review'] == '']

Columns:
	name	str
	review	str
	rating	float
	review_clean	str

Rows: Unknown

Data:
+-------------------------------+--------+--------+--------------+
|              name             | review | rating | review_clean |
+-------------------------------+--------+--------+--------------+
| SoftPlay Twinkle Twinkle E... |        |  5.0   |              |
|   Our Baby Girl Memory Book   |        |  5.0   |              |
| Summer Infant, Ultimate Tr... |        |  5.0   |              |
| Safety 1st Deluxe 4-in-1 B... |        |  1.0   |              |
| Northstate Superyard Playg... |        |  5.0   |              |
|   Munchkin Mozart Magic Cube  |        |  5.0   |              |
| Graco TotBloc Pack 'N Play... |        |  5.0   |              |
| Graco TotBloc Pack 'N Play... |        |  5.0   |              |
| Prince Lionheart Table Edg... |        |  2.0   |              |
| BABYBJORN Toilet Trainer -... |        |  5.0   |              |
+-------------------------------+--------+--------+--------------+
[? rows x 4 columns]
Note: Only the head of the SFrame is printed. This SFrame is lazily evaluated.
You can use sf.materialize() to force materialization.

In [25]:
products = products.fillna('review','')  # fill in N/A's in the review column
products = products.fillna('review_clean','')  # fill in N/A's in the review column

In [26]:
products

Columns:
	name	str
	review	str
	rating	float
	review_clean	str
	sentiment	int

Rows: 166752

Data:
+-------------------------------+-------------------------------+--------+
|              name             |             review            | rating |
+-------------------------------+-------------------------------+--------+
|     Planetwise Wipe Pouch     | it came early and was not ... |  5.0   |
| Annas Dream Full Quilt wit... | Very soft and comfortable ... |  5.0   |
| Stop Pacifier Sucking with... | This is a product well wor... |  5.0   |
| Stop Pacifier Sucking with... | All of my kids have cried ... |  5.0   |
| Stop Pacifier Sucking with... | When the Binky Fairy came ... |  5.0   |
| A Tale of Baby's Days with... | Lovely book, it's bound ti... |  4.0   |
| Baby Tracker&reg; - Daily ... | Perfect for new parents. W... |  5.0   |
| Baby Tracker&reg; - Daily ... | A friend of mine pinned th... |  5.0   |
| Baby Tracker&reg; - Daily ... | This has been an easy way ... |  4.0   |
| Baby Tracker&reg; - Daily ... | I love this journal and ou... |  4.0   |
+-------------------------------+-------------------------------+--------+
+-------------------------------+-----------+
|          review_clean         | sentiment |
+-------------------------------+-----------+
| it came early and was not ... |     1     |
| Very soft and comfortable ... |     1     |
| This is a product well wor... |     1     |
| All of my kids have cried ... |     1     |
| When the Binky Fairy came ... |     1     |
| Lovely book its bound tigh... |     1     |
| Perfect for new parents We... |     1     |
| A friend of mine pinned th... |     1     |
| This has been an easy way ... |     1     |
| I love this journal and ou... |     1     |
+-------------------------------+-----------+
[166752 rows x 5 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [27]:
products = products[products['rating'] != 3]

In [28]:
products['sentiment'] = products['rating'].apply(lambda rating : +1 if rating > 3 else -1)

In [29]:
train_data, test_data = products.random_split(.8, seed=1)

In [30]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(token_pattern=r'\b\w+\b')
    # Use this token pattern to keep single-letter words
# First, learn vocabulary from the training data and assign columns to words
# Then convert the training data into a sparse matrix
train_matrix = vectorizer.fit_transform(train_data['review_clean'])
# Second, convert the test data into a sparse matrix, using the same word-column mapping
test_matrix = vectorizer.transform(test_data['review_clean'])

In [32]:
train_matrix.shape

(133416, 121712)

In [35]:
from sklearn import linear_model

In [36]:
sentimental_model = linear_model.LogisticRegression()

In [37]:
sentimental_model.fit(train_matrix, train_data['sentiment'])

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [45]:
import pandas as pd
coefficients = pd.DataFrame(sentimental_model.coef_).transpose()

In [50]:
positive_coef = coefficients[coefficients>=0].dropna().count()
negative_coef = coefficients[coefficients<0].dropna().count()

In [51]:
print positive_coef
print negative_coef

0    85929
dtype: int64
0    35783
dtype: int64


In [52]:
sample_test_data = test_data[10:13]
print sample_test_data

+-------------------------------+-------------------------------+--------+
|              name             |             review            | rating |
+-------------------------------+-------------------------------+--------+
|   Our Baby Girl Memory Book   | Absolutely love it and all... |  5.0   |
| Wall Decor Removable Decal... | Would not purchase again o... |  2.0   |
| New Style Trailing Cherry ... | Was so excited to get this... |  1.0   |
+-------------------------------+-------------------------------+--------+
+-------------------------------+-----------+
|          review_clean         | sentiment |
+-------------------------------+-----------+
| Absolutely love it and all... |     1     |
| Would not purchase again o... |     -1    |
| Was so excited to get this... |     -1    |
+-------------------------------+-----------+
[3 rows x 5 columns]



In [55]:
sample_test_data[0]['review']

'Absolutely love it and all of the Scripture in it.  I purchased the Baby Boy version for my grandson when he was born and my daughter-in-law was thrilled to receive the same book again.'

In [56]:
sample_test_data[1]['review']

'Would not purchase again or recommend. The decals were thick almost plastic like and were coming off the wall as I was applying them! The would NOT stick! Literally stayed stuck for about 5 minutes then started peeling off.'

In [58]:
sample_test_matrix = vectorizer.transform(sample_test_data['review_clean'])
scores = sentimental_model.decision_function(sample_test_matrix)
print scores

[  5.60690029  -3.14219746 -10.40284605]


In [60]:
pd.Series(scores).apply(lambda rating : +1 if rating > 0 else -1)

0    1
1   -1
2   -1
dtype: int64

In [61]:
sentimental_model.predict(sample_test_matrix)

array([ 1, -1, -1], dtype=int64)

In [62]:
import numpy as np

In [63]:
np.exp(scores)

array([  2.72298882e+02,   4.31877903e-02,   3.03459939e-05])

In [65]:
print (1/(1 + np.exp(-scores)))

[  9.96341002e-01   4.13998234e-02   3.03450731e-05]


In [104]:
sample_test_matrix = vectorizer.transform(test_data['review_clean'])
scores_test = sentimental_model.predict_proba(test_matrix)
test_data['predicted_sentiment'] = sentimental_model.predict(test_matrix)

In [105]:
test_data.head()

Columns:
	name	str
	review	str
	rating	float
	review_clean	str
	sentiment	int
	proba	float
	predicted_sentiment	int

Rows: 10

Data:
+-------------------------------+-------------------------------+--------+
|              name             |             review            | rating |
+-------------------------------+-------------------------------+--------+
| Baby Tracker&reg; - Daily ... | This has been an easy way ... |  4.0   |
| Baby Tracker&reg; - Daily ... | I love this journal and ou... |  4.0   |
| Nature's Lullabies First Y... | I love this little calende... |  5.0   |
| Nature's Lullabies Second ... | I had a hard time finding ... |  5.0   |
|  Lamaze Peekaboo, I Love You  | One of baby's first and fa... |  4.0   |
|  Lamaze Peekaboo, I Love You  | My son loved this book as ... |  5.0   |
|  Lamaze Peekaboo, I Love You  | Our baby loves this book &... |  5.0   |
| SoftPlay Giggle Jiggle Fun... | This bear is absolutely ad... |  2.0   |
| SoftPlay Peek-A-Boo Where'... | I bought two for recent ba... |  5.0   |
| Baby's First Year Undated ... | I searched high and low fo... |  5.0   |
+-------------------------------+-------------------------------+--------+
+-------------------------------+-----------+----------------+---------------------+
|          review_clean         | sentiment |     proba      | predicted_sentiment |
+-------------------------------+-----------+----------------+---------------------+
| This has been an easy way ... |     1     | 0.783834010702 |          1          |
| I love this journal and ou... |     1     | 0.999999283393 |          1          |
| I love this little calende... |     1     | 0.934321039305 |          1          |
| I had a hard time finding ... |     1     | 0.999978650202 |          1          |
| One of babys first and fav... |     1     | 0.980334197991 |          1          |
| My son loved this book as ... |     1     | 0.999953860108 |          1          |
| Our baby loves this book  ... |     1     | 0.998746939101 |          1          |
| This bear is absolutely ad... |     -1    | 0.808321969778 |          1          |
| I bought two for recent ba... |     1     | 0.998480409487 |          1          |
| I searched high and low fo... |     1     | 0.997326499473 |          1          |
+-------------------------------+-----------+----------------+---------------------+
[10 rows x 7 columns]

In [106]:
print scores_test[7]

[ 0.19167803  0.80832197]


In [107]:
scores_test.shape

(33336L, 2L)

In [108]:
test_data.shape

(33336, 7)

In [109]:
test_data['proba'] = scores_test[:,1]

In [110]:
test_data.sort('proba', ascending=False).print_rows(num_rows=20)

+-------------------------------+-------------------------------+--------+
|              name             |             review            | rating |
+-------------------------------+-------------------------------+--------+
| Graco FastAction Fold Jogg... | Graco's FastAction Jogging... |  5.0   |
| Graco Pack 'n Play Element... | My husband and I assembled... |  4.0   |
| Freemie Hands-Free Conceal... | I absolutely love this pro... |  5.0   |
| Baby Einstein Around The W... | I am so HAPPY I brought th... |  5.0   |
| Evenflo 6 Pack Classic Gla... | It's always fun to write a... |  5.0   |
| Fisher-Price Cradle 'N Swi... | My husband and I cannot st... |  5.0   |
| Mamas &amp; Papas 2014 Urb... | After much research I purc... |  4.0   |
| Britax 2012 B-Agile Stroll... | [I got this stroller for m... |  4.0   |
| Simple Wishes Hands-Free B... | I just tried this hands fr... |  5.0   |
| Diono RadianRXT Convertibl... | I bought this seat for my ... |  5.0   |
| Roan Rocco Classic Pram

In [111]:
test_data.sort('proba').print_rows(num_rows=20)

+-------------------------------+-------------------------------+--------+
|              name             |             review            | rating |
+-------------------------------+-------------------------------+--------+
| Fisher-Price Ocean Wonders... | We have not had ANY luck w... |  2.0   |
| Levana Safe N'See Digital ... | This is the first review I... |  1.0   |
| Safety 1st Exchangeable Ti... | I thought it sounded great... |  1.0   |
| Adiri BPA Free Natural Nur... | I will try to write an obj... |  2.0   |
| VTech Communications Safe ... | This is my second video mo... |  1.0   |
| The First Years True Choic... | Note: we never installed b... |  1.0   |
| Safety 1st High-Def Digita... | We bought this baby monito... |  1.0   |
| Cloth Diaper Sprayer--styl... | I bought this sprayer out ... |  1.0   |
| Motorola Digital Video Bab... | DO NOT BUY THIS BABY MONIT... |  1.0   |
| Philips AVENT Newborn Star... | It's 3am in the morning an... |  1.0   |
| Cosco Alpha Omega Elite

In [119]:
correct_predict = test_data[test_data['sentiment'] == test_data['predicted_sentiment']].num_rows()

In [120]:
total_data = test_data.num_rows()

In [124]:
accuracy = correct_predict / float(total_data)
print accuracy

0.932265418766


In [125]:
significant_words = ['love', 'great', 'easy', 'old', 'little', 'perfect', 'loves', 
      'well', 'able', 'car', 'broke', 'less', 'even', 'waste', 'disappointed', 
      'work', 'product', 'money', 'would', 'return']

In [126]:
len(significant_words)

20

In [128]:
vectorizer_word_subset = CountVectorizer(vocabulary=significant_words) # limit to 20 words
train_matrix_word_subset = vectorizer_word_subset.fit_transform(train_data['review_clean'])
test_matrix_word_subset = vectorizer_word_subset.transform(test_data['review_clean'])

In [129]:
simple_model = linear_model.LogisticRegression()
simple_model.fit(train_matrix_word_subset, train_data['sentiment'])

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [130]:
simple_model_coef_table = pd.DataFrame({'word':significant_words,
                                         'coefficient':simple_model.coef_.flatten()})

In [132]:
simple_model_coef_table.sort('coefficient')

C:\Users\Dhaval-PC\Anaconda2\envs\gl-env\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':


coefficient          word
14    -2.348298  disappointed
19    -2.109331        return
13    -2.033699         waste
10    -1.651576         broke
17    -0.898031         money
15    -0.621169          work
12    -0.511380          even
18    -0.362167         would
16    -0.320556       product
11    -0.209563          less
9      0.058855           car
3      0.085513           old
8      0.190909          able
7      0.503760          well
4      0.520186        little
1      0.944000         great
2      1.192538          easy
0      1.363690          love
5      1.509812       perfect
6      1.673074         loves

In [134]:
train_data['predicated_sentiment'] = sentimental_model.predict(train_matrix)
correct_predict_train = train_data[train_data['sentiment'] == train_data['predicated_sentiment']].num_rows()
total_data_train = train_data.num_rows()
accuracy_train = correct_predict_train / float(total_data_train)
print accuracy_train

0.967964861786


In [136]:
train_data['simple_predicated_sentiment'] = simple_model.predict(train_matrix_word_subset)
correct_predict_train_simple = train_data[train_data['sentiment'] == train_data['simple_predicated_sentiment']].num_rows()
total_data_train = train_data.num_rows()
accuracy_train_simple = correct_predict_train_simple / float(total_data_train)
print accuracy_train_simple

0.866822570007


In [137]:
test_data['simple_predicated_sentiment'] = simple_model.predict(test_matrix_word_subset)
correct_predict_test_simple = test_data[test_data['sentiment'] == test_data['simple_predicated_sentiment']].num_rows()
total_data_test = test_data.num_rows()
accuracy_test_simple = correct_predict_test_simple / float(total_data_test)
print accuracy_test_simple

0.869360451164


In [138]:
mcc_count = test_data[test_data['sentiment'] == 1].num_rows()
total_data_test = test_data.num_rows()
accuracy_mcc = mcc_count / float(total_data_test)
print accuracy_mcc

0.842782577394
